### ISSUE TITLE
Not working with Streamlit 1.12 and python 3.8

### ISSUE THREAD

**Issue by protestToViolence** [arnaudmiribel/streamlit-faker#1]
Hey, I got the following error while running in my conda environment.
ImportError: cannot import name 'get_streamlit_faker' from partially initialized module 'streamlit_faker'

I am still searching for the reason. Any help woud greatly be appreciated.

Thank you

**Comment by arnaudmiribel** [comment]
Hey @protestToViolence! Not sure where this could come from. Can you try and upgrade python to 3.9 and see if that solves anything? Here's what I'm using: `streamlit==1.13.0` and `python==3.9.13`

**Comment by blackary** [comment]
@protestToViolence This could be related to a dependency issue, which should be resolved with the recent 0.0.2 release -- could you try upgrading to 0.0.2 and see if you still encounter this issue?
